### ISSUE TITLE
covert_cpbitmap.py执行报错

### ISSUE THREAD

**Issue by ReylinXu** [sh00tg0a1/cpbitmap_convertor#1]
```
Traceback (most recent call last):
  File "covert_cpbitmap.py", line 65, in <module>
    func2()
  File "covert_cpbitmap.py", line 63, in func2
    img.save(sys.argv[2])
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 1423, in save
    raise KeyError(ext) # unknown extension
KeyError: ''
```

运行环境：
Windows 10 Pro (64-bit)
Python: 2.7.16
PIL: 1.1.7

**Comment by sh00tg0a1** [comment]
你好 @ReylinXu ，我是在 Mac 下运行的，我还没有测试过 Windows 10 的环境。看这个错误，好像是文件名写错了，第二个参数你写的是 xxx.png 吗

**Comment by ReylinXu** [comment]
不好意思，确实是我的输出文件名写错了。您的脚本非常不错，能正常工作，谢谢！
